version: '3'

services:
  
  build_container:
    environment:
    - OS_AUTH_URL="${OS_AUTH_URL}"
    - OS_CACERT="${OS_CACERT}"
    - OS_DOMAIN_NAME="${OS_DOMAIN_NAME}"
    - OS_TENANT_NAME="${OS_TENANT_NAME}"
    container_name: build_container
    image: jupytercloud-project/build-container:latest
    ports:
    - "127.0.0.1:6000-6020:6000-6020"
    volumes:
    - .:/src
    - ./packer_cache:/packer_cache
    - ./qemu-registry:/qemu-registry
    command: /bin/bash /src/tools/hashicorp/packer/images/openstack-jupytercloud-image/build.bash
