version: 2.1

executors:
  vm:
    machine:
      enabled: true
      image: circleci/classic:latest

jobs:
  build:
    executor: vm
    shell: /bin/bash --login -eo pipefail
    environment:
      ARTIFACT_DIR: ./qemu-registry
      GHR: github.com/tcnksm/ghr
      DKR: https://github.com/jupytercloud-project/build-container/releases/download/0.0.1/jupytercloud-project_build-container_latest.dkr
      SRC: https://github.com/jupytercloud-project/openstack-alpine-image/releases/download/0.0.1/openstack-alpine-image-3.9.3.raw
    steps:
    - checkout
    - run:
        name: 'Define environment variables'
        command: |
          echo 'export RELEASE_VERSION=0.0.1' >> ${BASH_ENV}
    - run:
        name: 'Installing dependencies'
        command: |
          pip install python-openstackclient
    - run:
        name: 'Uploading source image'
        command: |
          curl --location \
               --output ./cacert.pem \
               ${OS_CACERT}
          ls -alFh
          openstack --version
          openstack --os-cacert ./cacert.pem \
                    --os-image-api-version 1 \
                    image create \
                    --location ${SRC}
                    openstack-alpine-image-3.9.3
    - run:
        name: 'Fetching build container image'
        command: |
          curl --location ${DKR} | docker load
    - run:
        name: 'Running build container'
        command: |
          docker-compose up
    - run:
        name: 'Publishing release on GitHub'
        command: |
          go get ${GHR} && \
          VERSION=${RELEASE_VERSION} \
          ghr -t ${GITHUB_TOKEN} \
              -u ${CIRCLE_PROJECT_USERNAME} \
              -r ${CIRCLE_PROJECT_REPONAME} \
              -c ${CIRCLE_SHA1} \
              -delete \
              ${RELEASE_VERSION} \
              ${ARTIFACT_DIR}/
